### ISSUE TITLE
Failed to run examples

### ISSUE THREAD

**Issue by MinghuaWang** [lizhuohua/rust-ffi-checker#1]
Hi, 
 I've successfully built the project as instructed but failed to run shipped examples. For instance, if I tried examples/vec_test:
```
cd examples/vec-test
cargo ffi-checker
```
I got the error :
```
"CommandLine Error: Option 'print-summary-global-ids' registered more than once! 
LLVM ERROR: inconsistency in registered CommandLine options".
```

Did I miss anything? My testing env was on a Ubuntu 22.04 64-bit machine, with llvm-13 compiled from source code and installed.  Thanks!

**Comment by lizhuohua** [comment]
Hi,

My guess is that your LLVM was not compiled with shared libraries enabled. Try to run `llvm-config --shared-mode` and see whether the output is "shared". Otherwise, you need to recompile your LLVM.

**Comment by MinghuaWang** [comment]
Hi, 
I recompiled llvm 13 with the following command:
```
mkdir build; cd build;
cmake -G "Unix Makefiles" -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON -DCMAKE_BUILD_TYPE=Release ../llvm
make -j4
sudo make install
```
After the build process, I double-checked `llvm-config --shared-mode` and it was `shared`. However, the same error still exists.  Could you provide me with your experiment settings? Thanks!

**Comment by lizhuohua** [comment]
It seems like this is a [long-standing problem of LLVM](https://discourse.llvm.org/t/can-something-be-done-with-the-inconsistency-in-registered-commandline-options-error/1720). I also have no idea what's going on.

I didn't compile LLVM on my own. I simply installed it via `apt-get`. You may refer to [this script](https://github.com/lizhuohua/rust-ffi-checker/blob/master/.github/workflows/build.yml).

**Comment by MinghuaWang** [comment]
I might figure out one solution to this problem. I added the `no-llvm-linking` feature for llvm-sys (as follows) and tested the examples again, and the error finally disappeared. 
```
// Cargo.toml:
-llvm-sys = "130"
+llvm-sys = { version = "130", features = ["no-llvm-linking"] }
```
The problem was introduced by compiling llvm-sys. If it was static linked against llvm, the final built binary would have two copies of llvm, one was that static linked, and the other was dynamic linked, and this would lead to the error: 
```
: CommandLine Error: Option 'xxx' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**Comment by lizhuohua** [comment]
Great. Thank you very much for your efforts.
Then I will close this issue.
